# Generated by Django 3.2.4 on 2021-06-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_companyregister_confpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyregister',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='companyregister',
            name='phone',
        ),
    ]
